import { spawn, type ChildProcess } from "node:child_process";
import { once } from "node:events";
import { mkdtemp, readFile, rename, rm, writeFile } from "node:fs/promises";
import { createServer } from "node:net";
import { tmpdir } from "node:os";
import { join } from "node:path";
import {
  CHAIN_DEFAULTS,
  KNOWN_CHAINS,
  controllerOf,
  maskUrls,
  parseConfig,
  resolveValue,
  type AppConfig,
  type ChainConfig,
} from "../config";

/**
 * The pieces of running the installed engine (`ENGINE.md`, Start):
 * `engine.toml` from the configuration, the engine's allow-listed
 * environment, `migrate`, `verify`, the spawn, and stopping it. The
 * supervisor puts them in order and decides what an exit means.
 */

export class EngineLaunchError extends Error {}

/**
 * Before `config.json` has a chain, the one the environment names, as the
 * first builds took it: `TRIPWIRE_RPC_HTTP` (and `TRIPWIRE_RPC_WS`, which
 * turns on mempool watching, never responding), `TRIPWIRE_CHAIN_ID` and
 * `TRIPWIRE_RESPONSE_MODE`. A chain in the file always wins.
 */
export function withEnvironmentChain(
  config: AppConfig,
  env: NodeJS.ProcessEnv,
): AppConfig {
  if (config.chain || !env.TRIPWIRE_RPC_HTTP) return config;
  const chainId = Number(env.TRIPWIRE_CHAIN_ID ?? 1);
  if (!Number.isSafeInteger(chainId) || chainId < 1) {
    throw new EngineLaunchError(
      `TRIPWIRE_CHAIN_ID must be a chain id, not "${env.TRIPWIRE_CHAIN_ID}".`,
    );
  }
  const mode = env.TRIPWIRE_RESPONSE_MODE ?? config.response.mode;
  if (mode !== "notify" && mode !== "prepare" && mode !== "send") {
    throw new EngineLaunchError(
      `TRIPWIRE_RESPONSE_MODE must be notify, prepare or send, not "${mode}".`,
    );
  }
  const ws = Boolean(env.TRIPWIRE_RPC_WS);
  return parseConfig({
    ...config,
    chain: {
      ...CHAIN_DEFAULTS,
      chainId,
      rpcHttp: "env:TRIPWIRE_RPC_HTTP",
      rpcWs: ws ? "env:TRIPWIRE_RPC_WS" : null,
    },
    response: { ...config.response, mode },
    mempool: { enabled: ws, respond: false },
  });
}

/**
 * `engine.toml` for this run (`ENGINE.md`, engine.toml). Every secret is
 * an `env:` reference, so the file holds none; null values are left out
 * so the engine's own defaults apply.
 */
export function engineToml(
  config: AppConfig & { chain: ChainConfig },
  options: {
    dataDir: string;
    port: number;
    local: boolean;
    keysPassphrase: boolean;
  },
): string {
  const { chain, response } = config;
  const controller = controllerOf(chain);
  const text = (value: string) => JSON.stringify(value);
  const lines = [
    "# Generated by Tripwire from config.json on every start. Edits are overwritten.",
    "",
    "[chain]",
    `chain_id = ${chain.chainId}`,
    'rpc_http = "env:TRIPWIRE_RPC_HTTP"',
    ...(chain.rpcWs ? ['rpc_ws = "env:TRIPWIRE_RPC_WS"'] : []),
    `poll_interval_ms = ${chain.pollIntervalMs}`,
    ...(controller
      ? [
          `controller_address = ${text(controller.address)}`,
          `controller_deployed_block = ${controller.block}`,
        ]
      : []),
    "",
    "[database]",
    'url = "env:TRIPWIRE_DATABASE_URL"',
    // The local database is one session behind the pooler (DATABASE.md).
    ...(options.local ? ["max_connections = 1"] : []),
    "",
    "[data]",
    `dir = ${text(options.dataDir)}`,
    "",
    "[engine]",
    `bind = "127.0.0.1:${options.port}"`,
    "",
    "[response]",
    `mode = ${text(response.mode)}`,
    ...(response.key ? [`key = ${text(response.key)}`] : []),
    ...(response.maxFeeGwei !== null
      ? [`max_fee_gwei = ${response.maxFeeGwei}`]
      : []),
    ...(response.maxPriorityFeeGwei !== null
      ? [`max_priority_fee_gwei = ${response.maxPriorityFeeGwei}`]
      : []),
    `replacement_blocks = ${response.replacementBlocks}`,
    `max_attempts = ${response.maxAttempts}`,
    `submission = ${text(response.submission)}`,
    ...(response.privateEndpoints
      ? [
          `private_endpoints = [${response.privateEndpoints.map(text).join(", ")}]`,
        ]
      : []),
    "",
    "[retention]",
    `points_days = ${config.retention.pointsDays}`,
    `notifications_days = ${config.retention.notificationsDays}`,
    "",
    "[mempool]",
    `enabled = ${config.mempool.enabled}`,
    `respond = ${config.mempool.respond}`,
  ];
  if (options.keysPassphrase) {
    lines.push("", "[keys]", 'passphrase = "env:TRIPWIRE_KEYS_PASSPHRASE"');
  }
  return `${lines.join("\n")}\n`;
}

/**
 * Only what the engine needs reaches it (ENGINE.md, the engine's
 * environment), with every `env:` reference resolved.
 */
export function engineEnvironment(
  chain: ChainConfig,
  env: NodeJS.ProcessEnv,
  databaseUrl: string,
): NodeJS.ProcessEnv {
  const out: NodeJS.ProcessEnv = {
    PATH: env.PATH,
    TRIPWIRE_DATABASE_URL: databaseUrl,
    TRIPWIRE_RPC_HTTP: resolveValue(chain.rpcHttp, env, "chain.rpcHttp"),
  };
  if (chain.rpcWs) {
    out.TRIPWIRE_RPC_WS = resolveValue(chain.rpcWs, env, "chain.rpcWs");
  }
  if (env.TRIPWIRE_KEYS_PASSPHRASE) {
    out.TRIPWIRE_KEYS_PASSPHRASE = env.TRIPWIRE_KEYS_PASSPHRASE;
  }
  return out;
}

/** Writes a file whole: staged beside its name, then renamed, mode 0600. */
export async function writeWhole(path: string, text: string) {
  const staged = `${path}.${process.pid}`;
  await writeFile(staged, text, { mode: 0o600 });
  await rename(staged, path);
}

/** The interface secret once the engine has written it whole; null before. */
export async function readSecret(file: string): Promise<string | null> {
  const text = await readFile(file, "utf8").catch(() => "");
  const secret = text.trim();
  return /^[0-9a-f]{64}$/.test(secret) ? secret : null;
}

/** `engine.pid`: the running engine's pid, start time and binary. */
export interface PidRecord {
  pid: number;
  startedAt: string;
  binary: string;
}

export async function writePid(file: string, record: PidRecord) {
  await writeWhole(file, `${JSON.stringify(record)}\n`);
}

export async function readPid(file: string): Promise<PidRecord | null> {
  const text = await readFile(file, "utf8").catch(() => null);
  if (!text) return null;
  try {
    const record = JSON.parse(text) as PidRecord;
    return Number.isSafeInteger(record.pid) && record.pid > 0 ? record : null;
  } catch {
    // The first builds wrote the pid alone.
    const pid = Number(text.trim());
    return Number.isSafeInteger(pid) && pid > 0
      ? { pid, startedAt: "", binary: "tripwire-engine" }
      : null;
  }
}

/**
 * An engine left running by a server that was killed. It is stopped only
 * when its command line names the recorded binary; a pid reused by an
 * unrelated process is left alone. The file goes either way.
 */
export async function stopOrphan(pidFile: string): Promise<boolean> {
  const record = await readPid(pidFile);
  let stopped = false;
  if (record) {
    const cmdline = await readFile(`/proc/${record.pid}/cmdline`, "utf8").catch(
      () => "",
    );
    if (cmdline.split("\0").some((part) => part.endsWith(record.binary))) {
      signal(record.pid, "SIGTERM");
      for (let i = 0; i < 60 && alive(record.pid); i++) {
        await sleep(250);
      }
      if (alive(record.pid)) signal(record.pid, "SIGKILL");
      stopped = true;
    }
  }
  await rm(pidFile, { force: true });
  return stopped;
}

export function alive(pid: number) {
  try {
    process.kill(pid, 0);
    return true;
  } catch {
    return false;
  }
}

function signal(pid: number, name: NodeJS.Signals) {
  try {
    process.kill(pid, name);
  } catch {
    // Already gone.
  }
}

export function sleep(ms: number) {
  return new Promise((done) => setTimeout(done, ms));
}

/** A free loopback port: bound on port 0 and released. */
export function freePort(): Promise<number> {
  return new Promise((done, fail) => {
    const server = createServer();
    server.once("error", fail);
    server.listen(0, "127.0.0.1", () => {
      const address = server.address();
      const port = typeof address === "object" && address ? address.port : 0;
      server.close(() => done(port));
    });
  });
}

/** Runs one engine command to its end. */
export function runEngine(
  binary: string,
  args: string[],
  env: NodeJS.ProcessEnv,
): Promise<{ code: number | null; stdout: string; stderr: string }> {
  return new Promise((done, fail) => {
    const child = spawn(binary, args, {
      env,
      stdio: ["ignore", "pipe", "pipe"],
    });
    let stdout = "";
    let stderr = "";
    child.stdout.on("data", (chunk: Buffer) => (stdout += chunk.toString()));
    child.stderr.on("data", (chunk: Buffer) => (stderr += chunk.toString()));
    child.once("error", fail);
    child.once("close", (code) => done({ code, stdout, stderr }));
  });
}

export interface SpawnedEngine {
  child: ChildProcess;
  /** Resolves when the process has exited. */
  exited: Promise<{ code: number | null; signal: NodeJS.Signals | null }>;
}

/**
 * `tripwire-engine run` in its own process group, so a Ctrl+C reaches the
 * application only, which then stops the engine in order. Its output
 * arrives line by line.
 */
export function spawnEngine(options: {
  binary: string;
  configFile: string;
  env: NodeJS.ProcessEnv;
  onLine: (line: string) => void;
}): SpawnedEngine {
  const child = spawn(options.binary, ["run", "--config", options.configFile], {
    detached: true,
    stdio: ["ignore", "pipe", "pipe"],
    env: options.env,
  });
  for (const stream of [child.stdout, child.stderr]) {
    let rest = "";
    stream.on("data", (chunk: Buffer) => {
      rest += chunk.toString();
      const lines = rest.split("\n");
      rest = lines.pop() ?? "";
      for (const line of lines) options.onLine(line);
    });
    stream.on("end", () => {
      if (rest) options.onLine(rest);
      rest = "";
    });
  }
  const exited = once(child, "exit").then(([code, sig]) => ({
    code: code as number | null,
    signal: sig as NodeJS.Signals | null,
  }));
  // A binary that cannot run at all is an exit like any other.
  child.once("error", () => {});
  return { child, exited };
}

/** SIGTERM, which the engine answers by finishing its block; SIGKILL after the grace. */
export async function stopEngine(
  engine: SpawnedEngine,
  graceMs = 15_000,
): Promise<"stopped" | "killed"> {
  const { child, exited } = engine;
  if (child.exitCode !== null || child.signalCode !== null) return "stopped";
  child.kill("SIGTERM");
  let killed = false;
  const timer = setTimeout(() => {
    killed = true;
    child.kill("SIGKILL");
  }, graceMs);
  await exited;
  clearTimeout(timer);
  return killed ? "killed" : "stopped";
}

/** `tripwire-engine verify` (G2): the RPC checked against the chain, with no database. */
export interface VerifyResult {
  ok: boolean;
  chainId: number;
  head: number | null;
  receipts: string | null;
  ws: { ok: boolean; pending: boolean } | null;
  problems: { code: string; message: string }[];
}

export async function verifyChain(options: {
  binary: string;
  chain: ChainConfig;
  env: NodeJS.ProcessEnv;
  /** Whether to check the WebSocket too, when one is given. */
  checkWs?: boolean;
}): Promise<VerifyResult> {
  const chain =
    options.checkWs === false
      ? { ...options.chain, rpcWs: null }
      : options.chain;
  const dir = await mkdtemp(join(tmpdir(), "tripwire-verify-"));
  try {
    const configFile = join(dir, "engine.toml");
    // verify reads no database, but the configuration must name one.
    await writeWhole(
      configFile,
      engineToml(
        { ...parseConfig({ version: 1 }), chain },
        { dataDir: dir, port: 1, local: false, keysPassphrase: false },
      ),
    );
    const env = engineEnvironment(
      chain,
      options.env,
      "postgres://verify@127.0.0.1:1/unused",
    );
    const result = await runEngine(
      options.binary,
      ["verify", "--config", configFile],
      env,
    );
    const line = result.stdout.trim().split("\n").pop() ?? "";
    let parsed: {
      ok: boolean;
      chain_id: number;
      head: number | null;
      receipts: string | null;
      ws: { ok: boolean; pending: boolean } | null;
      problems: { code: string; message: string }[];
    };
    try {
      parsed = JSON.parse(line) as typeof parsed;
    } catch {
      return {
        ok: false,
        chainId: chain.chainId,
        head: null,
        receipts: null,
        ws: null,
        problems: [
          {
            code: "config_refused",
            message: maskUrls(
              (result.stderr || result.stdout).trim() ||
                `the engine exited with code ${result.code}`,
            ),
          },
        ],
      };
    }
    return {
      ok: parsed.ok,
      chainId: parsed.chain_id,
      head: parsed.head,
      receipts: parsed.receipts,
      ws: parsed.ws,
      // The engine's messages can quote the endpoint, key and all.
      problems: parsed.problems.map((p) => ({
        code: p.code,
        message:
          p.code === "wrong_chain"
            ? wrongChain(p.message)
            : maskUrls(p.message),
      })),
    };
  } finally {
    await rm(dir, { recursive: true, force: true });
  }
}

/** "this endpoint serves Base (8453), not Ethereum (1)", from the engine's wording. */
function wrongChain(message: string): string {
  const ids = /serves chain id (\d+).*configured for (\d+)/.exec(message);
  if (!ids) return maskUrls(message);
  const name = (id: string) => {
    const known = KNOWN_CHAINS.find((c) => String(c.id) === id);
    return known ? `${known.name} (${id})` : `chain ${id}`;
  };
  return `This endpoint serves ${name(ids[1]!)}, not ${name(ids[2]!)}.`;
}
